#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$"| grep -v ".ejs" | grep -v "node_modules")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

printf "\nValidating Javascript:\n\n"

# Check for eslint
ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
if [[ ! -x "$ESLINT" ]]; then
  printf "Please install ESlint (npm i --save --save-exact --dev eslint)\n"
  exit 1
fi

for FILE in $STAGED_FILES
do
  "$ESLINT" "$FILE"

  if [[ "$?" == 0 ]]; then
    printf "ESLint Passed: $FILE\n"
  else
    printf "ESLint Failed: $FILE\n"
    PASS=false
  fi
done

printf "\nJavascript validation completed!\n\n"

if ! $PASS; then
  printf "COMMIT FAILED: Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n\n"
  exit 1
else
  printf "COMMIT SUCCEEDED\n\n"
fi

exit $?
